package com.infore.mapper;

import com.infore.model.IotHisLoginOut;

public interface IotHisLoginOutMapper extends IotBaseMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table iot_his_loginout
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer idNum);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table iot_his_loginout
     *
     * @mbggenerated
     */
    int insert(IotHisLoginOut record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table iot_his_loginout
     *
     * @mbggenerated
     */
    int insertSelective(IotHisLoginOut record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table iot_his_loginout
     *
     * @mbggenerated
     */
    IotHisLoginOut selectByPrimaryKey(Integer idNum);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table iot_his_loginout
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(IotHisLoginOut record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table iot_his_loginout
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(IotHisLoginOut record);
}