package com.infore.mapper;

import com.infore.model.TestInfo;
import java.util.List;

public interface TestInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_info
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_info
     *
     * @mbggenerated
     */
    int insert(TestInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_info
     *
     * @mbggenerated
     */
    int insertSelective(TestInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_info
     *
     * @mbggenerated
     */
    TestInfo selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_info
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(TestInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_info
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(TestInfo record);

    List<TestInfo> queryByParams();
}